# Generated by Django 3.0.12 on 2021-02-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oscar_accounts', '0004_auto_20201109_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounttype',
            name='depth',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
